# Generated by Django 5.0.6 on 2025-10-18 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('TRANSPORTATION', 'Transportation')], help_text='Main category of carbon emission', max_length=20)),
                ('subcategory', models.CharField(help_text='Specific subcategory within the main category', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Numeric value of the entry (kWh, liters, km, etc.)', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (kWh, liters, km, etc.)', max_length=20)),
                ('co2_calculated', models.DecimalField(decimal_places=3, help_text='Calculated CO2 emissions in kg', max_digits=10)),
                ('date', models.DateField(help_text='Date of the carbon entry')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Entry',
                'verbose_name_plural': 'Carbon Entries',
                'db_table': 'carbon_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarbonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Goal title', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the goal')),
                ('target_reduction', models.DecimalField(decimal_places=2, help_text='Target CO2 reduction in kg per month', max_digits=10)),
                ('current_reduction', models.DecimalField(decimal_places=2, default=0, help_text='Current CO2 reduction achieved', max_digits=10)),
                ('start_date', models.DateField(help_text='Goal start date')),
                ('end_date', models.DateField(help_text='Goal end date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Goal',
                'verbose_name_plural': 'Carbon Goals',
                'db_table': 'carbon_goals',
                'ordering': ['-created_at'],
            },
        ),
    ]
