# Generated by Django 5.0.6 on 2025-10-18 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('notification_type', models.CharField(choices=[('ACHIEVEMENT', 'Achievement Unlocked'), ('CHALLENGE', 'Challenge Update'), ('FRIEND_REQUEST', 'Friend Request'), ('CLIMATE_ALERT', 'Climate Alert'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('SYSTEM', 'System Notification'), ('NEWS', 'News Update')], help_text='Type of notification', max_length=20)),
                ('title_template', models.CharField(help_text='Title template with placeholders', max_length=200)),
                ('content_template', models.TextField(help_text='Content template with placeholders')),
                ('icon', models.CharField(blank=True, help_text='Default icon for this template', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ACHIEVEMENT', 'Achievement Unlocked'), ('CHALLENGE', 'Challenge Update'), ('FRIEND_REQUEST', 'Friend Request'), ('CLIMATE_ALERT', 'Climate Alert'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('SYSTEM', 'System Notification'), ('NEWS', 'News Update')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('content', models.TextField(help_text='Notification content')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Notification priority', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when clicked')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for the notification', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
