# Generated by Django 5.0.6 on 2025-10-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('description', models.TextField(help_text='Alert description')),
                ('alert_type', models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('PRECIPITATION', 'Precipitation'), ('AIR_QUALITY', 'Air Quality'), ('SEA_LEVEL', 'Sea Level'), ('EXTREME_WEATHER', 'Extreme Weather')], help_text='Type of alert', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Alert severity', max_length=10)),
                ('location', models.CharField(help_text='Affected location', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('start_date', models.DateTimeField(help_text='Alert start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Alert end date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether alert is currently active')),
                ('source', models.CharField(help_text='Alert source', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='External alert ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Climate Alert',
                'verbose_name_plural': 'Climate Alerts',
                'db_table': 'climate_alerts',
                'ordering': ['-severity', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('CO2_LEVELS', 'CO2 Levels'), ('TEMPERATURE_ANOMALY', 'Temperature Anomaly'), ('SEA_LEVEL', 'Sea Level'), ('ARCTIC_ICE', 'Arctic Ice'), ('GREENHOUSE_GASES', 'Greenhouse Gases')], help_text='Type of climate data', max_length=30)),
                ('value', models.DecimalField(decimal_places=3, help_text='Data value', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('date', models.DateField(help_text='Date of the data point')),
                ('source', models.CharField(help_text='Data source (API name)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the data point')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Climate Data Point',
                'verbose_name_plural': 'Climate Data Points',
                'db_table': 'climate_data',
                'ordering': ['-date'],
                'unique_together': {('data_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClimateStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('GLOBAL_CO2', 'Global CO2'), ('GLOBAL_TEMP', 'Global Temperature'), ('ARCTIC_ICE_EXTENT', 'Arctic Ice Extent'), ('SEA_LEVEL_RISE', 'Sea Level Rise'), ('RENEWABLE_ENERGY', 'Renewable Energy')], help_text='Type of statistic', max_length=30)),
                ('current_value', models.DecimalField(decimal_places=3, help_text='Current value', max_digits=10)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=3, help_text='Previous period value', max_digits=10, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from previous period', max_digits=5, null=True)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('period', models.CharField(help_text='Time period (daily, weekly, monthly, yearly)', max_length=20)),
                ('date', models.DateField(help_text='Date of the statistic')),
                ('source', models.CharField(help_text='Data source', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Climate Statistic',
                'verbose_name_plural': 'Climate Statistics',
                'db_table': 'climate_statistics',
                'ordering': ['-date'],
                'unique_together': {('stat_type', 'period', 'date')},
            },
        ),
    ]
