# Generated by Django 5.0.6 on 2025-10-18 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='System prompt for the chatbot')),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum tokens per response')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, help_text='Response creativity (0.0 to 1.0)', max_digits=3)),
                ('include_user_data', models.BooleanField(default=True, help_text='Whether to include user carbon data in context')),
                ('include_climate_data', models.BooleanField(default=True, help_text='Whether to include climate data in context')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configurations',
                'db_table': 'chatbot_configs',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], help_text='Message role', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('session_id', models.CharField(help_text='Chat session identifier', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Number of tokens used for this message', null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=2, help_text='Response time in seconds', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Session title (auto-generated)', max_length=200)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages in session')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens used in session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
